### ISSUE TITLE
Not available on CRAN

### ISSUE THREAD

**Issue by yovizzle** [r-lib/async#56]
When attempting to do install.packages('async'), I get the following:

Warning in install.packages ```
:
  package ‘async’ is not available (for R version 3.6.3)
```

Is there an alternate way to install the package? Thanks!

**Comment by gaborcsardi** [comment]
You can use the remotes package to install it from GitHub:

```r
remotes::install_github("r-lib/async")
```

**Comment by yovizzle** [comment]
Great. Thank you
